<?php include "header.frag.html" ?>
<h3>About Us</h3>
<p>grAID Higher is a student-led tutoring organisation operating in the southwest. University students provide free tuition to secondary school pupils. Secondary school pupils of any age can apply for tuition with grAID Higher. Secondary schools can be part of grAID Higher irrespective of their location and all students are welcome of any level of ability and socioeconomic status. </p>

<h3>Our Ethos</h3>
<p>At grAID Higher we firmly believe in giving all children the opportunity to maximise their education and we feel that university students providing free tuition is an excellent way to do this on a larger scale.  We also feel that having university students tutor, who are still students themselves, will increase accessibility to learning for pupils. Also the one to one tuition will benefit those pupils who struggle to learn in a classroom environment. Furthermore, university students have first hand experience of life as a current student and will be able to provide a certain degree of advice and support regarding university to pupils who are considering this route or even those in the process of applying. Overall, grAID Higher is as much a universal scheme as possible with the aim of providing additional support and education to as many children as possible across Plymouth and the Southwest. </p>

<h3>Our Aims </h3>
<p>This year grAID Higher is in its infancy and for the academic year 2012-2013 will be piloted at Eggbuckland Community College. Student tutors are going to be recruited from University College Marjon and the University of Plymouth. In the next two years we aim to involve the schools inclusive of the Link Partnership, which are St Boniface, Notre Dame, Devonport High School for Girls and . In the next five years we aim to roll out grAID Higher to other schools in Plymouth and also recruit student tutors from Peninsula Medical School and Plymouth College of Art and Design. Over the next 10 years we aim to expand outside of Plymouth to other areas of the Southwest such as Bristol and Exeter. </p>
<?php include "footer.frag.html" ?>
